version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=43.204.221.192
      - WEBHOOK_URL=http://43.204.221.192:5678/
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres_db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8nuser
      - DB_POSTGRESDB_PASSWORD=n8npassword # UPDATE WITH YOUR ACTUAL PASSWORD
    external_links:
      - postgres_db:postgres_db
    networks:
      - app_network
      - scraper_network

  scraper:
    build: .
    restart: always
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    volumes:
      - ./debug:/app/debug
      - ./submitted_projects_cache.json:/app/submitted_projects_cache.json
    networks:
      - scraper_network

networks:
  scraper_network:
    driver: bridge
  app_network:
    external: true

volumes:
  n8n_data:
